name: game-elite
favicon: null
layout_spectrum: 0.6214032401330769
typography_spectrum: 0.08688275516033173
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f7eac0'
    - '#2c2c2c'
    - '#696969'
    - '#949494'
  brandStrength: 0.5174671160057187
  lightness: 0.49871674994938076
  saturation: 0.625
  rhythmicContrast: 0.3166954340413213
purpose: []
