name: game-elite
favicon: null
layout_spectrum: 0.6214032401330769
typography_spectrum: 0.08688275516033173
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a66638'
    - '#f5a96f'
    - '#604317'
    - '#fffde6'
    - '#372109'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
